Repository wp-cli/db-command, pull requests merged in 2018-10, with the labels that each got.

#117 Add links to mysql documentation
  src/DB_Command.php
Labels: scope:documentation

#119 Add new `db clean` to `README.md` and configuration files
  .github/settings.yml
  README.md
  composer.json
Labels: command:db-clean, scope:documentation

#118 Fix issue #107
  features/db-size.feature
  src/DB_Command.php
Labels: command:db-size

#121 Add support for Probot `move` command
  .github/move.yml
Labels: scope:distribution
