Repository wp-cli/db-command, pull requests merged in 2019-04, with the labels that each got.

#136 Fix db connection error tests for WP >= 5.2
  features/db.feature
Labels: scope:testing

#137 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#134 Update all-tables option output
  features/db-size.feature
  src/DB_Command.php
Labels: command:db-size

#140 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#141 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  db-command.php
  phpcs.xml.dist
  src/DB_Command.php
Labels: scope:testing

#135 fix typo in WP_CLI classname
  src/DB_Command.php
Labels: bug

#143 Update README.md file
  README.md
Labels: scope:documentation
